### ISSUE TITLE
Tims Assets

### ISSUE THREAD

**Issue by AlexejWieber** [Ultraschall-VR/Echosystem-Resonance#255]
- Checken [DONE] 
- Send Tim the list [DONE]
- Demand Orpheus .FBX [DONE]

**Comment by DemianBasse** [comment]
In General:
  - Naming: "Objekt_Material"
  - Keine No Name Materials
  - Kein Cinema Editor mit exportieren
  - Orpheus exportieren + Schleife

ANDROID_FIXED:
  -Arm: Innen normals umgedreht
  -normals unten

CAVE:
  - No Name Material

CORE FORMATION:
  - No Name Material

FLORA_SIZE_1-3:
  - Materials Naming

FLORA_SLINGS_1-5:
  - Materials Naming

PLAYERHAND_LEFT:
  - Normals checken

WHALEWIP:
  - Hierarchy aufräumen!
  - Ungenutzte Meshes herausnehmen
  - Mesh Auflösung runter: High -> Low Poly

SINGLEROCKS:
  - No Name Materials

STACKS:
  - No Name Materials

**Comment by DemianBasse** [comment]
Sent the email, setting the deadline for reworked assets to the 25th of April
