### ISSUE TITLE
UG vs GbR Checken

### ISSUE THREAD

**Issue by albertoelschlaegel** [Ultraschall-VR/Echosystem-Resonance#47]

**Comment by DemianBasse** [comment]
Informationen: 
- [Hinweise zur UG Gründung](https://www.stuttgart.ihk24.de/fuer-unternehmen/recht-und-steuern/gesellschaftsrecht-unternehmensformen/wahl-der-rechtsform-gesellschaftsrecht/gruendung-gmbh-ug-685004)
